use_frameworks!

target 'NKOverWrapLogger_Example' do
  pod 'NKOverWrapLogger', :path => '../'

  target 'NKOverWrapLogger_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
